// TASK-007: ComplianceFilter - Risk Assessment and Filtering
import type { AmazonProduct } from './research';

export interface ComplianceResult {
  passed: boolean;
  reasons: string[];
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  filtersFailed: string[];
}

// VERO Brand Lists
const VERO_TIER1_BRANDS = [
  'Apple', 'Samsung', 'Sony', 'Microsoft', 'Google', 'Amazon',
  'Nintendo', 'PlayStation', 'Xbox',
  'Nike', 'Adidas', 'Under Armour', 'Puma', 'Reebok', 'New Balance', 'Jordan', 'Yeezy',
  'Louis Vuitton', 'Gucci', 'Chanel', 'Prada', 'Hermès', 'Hermes', 'Burberry', 'Versace', 'Dior', 'Fendi', 'Balenciaga', 'Givenchy',
  'Rolex', 'Cartier', 'Tiffany', 'Omega', 'TAG Heuer', 'Patek Philippe',
  'Lego', 'Disney', 'Marvel', 'Star Wars', 'Pokemon', 'Pokémon', 'Hello Kitty', 'Sanrio', 'Barbie', 'Hot Wheels', 'Mattel', 'Hasbro'
];

const VERO_TIER2_BRANDS = [
  'Bose', 'JBL', 'Beats', 'Dyson', 'LG', 'Panasonic', 'Canon', 'Nikon', 'GoPro', 'DJI', 'Garmin', 'Fitbit',
  'North Face', 'Patagonia', 'Columbia', 'Lululemon', 'Ralph Lauren', 'Polo', 'Tommy Hilfiger', 'Calvin Klein', 'Lacoste', 'Oakley', 'Ray-Ban',
  'MAC', 'Estée Lauder', 'Clinique', 'Urban Decay', 'Too Faced', 'Benefit', 'NARS', 'Bobbi Brown',
  'Keurig', 'KitchenAid', 'Yeti', 'Hydroflask', 'Instant Pot', 'Vitamix', 'Ninja',
  'Tesla', 'BMW', 'Mercedes', 'Audi', 'Ford', 'Harley Davidson', 'Harley-Davidson'
];

const VERO_TIER3_BRANDS = [
  'NFL', 'NBA', 'MLB', 'NHL', 'NCAA',
  'Peppa Pig', 'Paw Patrol', 'SpongeBob', 'Sesame Street', 'Dora',
  'DeWalt', 'Milwaukee', 'Makita', 'Bosch', 'Snap-On',
  'Coleman', 'REI', 'Osprey', 'Kelty',
  'Fender', 'Gibson', 'Taylor', 'Martin'
];

// Full VERO brand list (3205 brands merged from VeroList.txt + VeroListNew.txt)
export const VERO_BRANDS = [
  '1 body',
  '162751656526 - 2" thick fat grips - made from comfortable and durable non-slip silicone rubber',
  '183064760552 - professional waiters corkscrew by barvivo - this bottle opener for beer and wine',
  '1byone',
  '252919355403',
  '253111318226',
  '2DS',
  '3 Sprouts',
  '321 strong',
  '3DS',
  '3m',
  '3M Company',
  '3m deutschland gmbh',
  '3m oral care',
  '3Skulls Paintball',
  '3sprouts',
  '4knines',
  '4Life',
  '5 Second Fix',
  '66fit',
  '8-in-1',
  'a-szcxtop',
  'Ã–ko-Tex',
  'a.b. mckinley',
  'a.r.m.s.',
  'AAT - The Association of Acounting Technicians',
  'ab flex',
  'abcuts',
  'abercrombie',
  'Abercrombie & Fitch',
  'abercrombie amp; fitch',
  'acc u rate',
  'access denied',
  'accuteck',
  'ace',
  'Action Mining Services Inc.',
  'active brothers aps',
  'Aculief',
  'adafruit',
  'adafruit industries, llc',
  'adeept',
  'adidas',
  'Adobe',
  'adore by nat',
  'ADT',
  'aduro',
  'aduro sport',
  'AEM',
  'aerogarden',
  'after blaster',
  'aftershokz',
  'Agora LLC',
  'aguacatina',
  'ahava',
  'aidance skincare',
  'aikou',
  'air dragon',
  'air force one air conditi',
  'Air Force One Air Conditioning',
  'aira brand',
  'airbrushs',
  'aircraft technical publis',
  'Aircraft Technical Publishers',
  'airplus',
  'airwave',
  'ak47',
  'akna',
  'akribos',
  'Alaska Airlines',
  'albolene',
  'aleppo',
  'aleratec',
  'aleratec inc.',
  'Aleratec, Inc.',
  'alex and ani',
  'Alex Perez',
  'Alfresco Heating',
  'ALIENTECH SRL',
  'Align',
  'all saints',
  'All Saints (Retail) Ltd',
  'ALM Productions',
  'aloe cadabra',
  'Aloe of America, Inc. & Forever Living Products Int\'l.',
  'alps',
  'alta',
  'altruism',
  'Always',
  'Always Discreet',
  'amabrush',
  'amapodo',
  'Amari Bliss',
  'ambiente',
  'AMC Photographics Limited',
  'amenitee',
  'American Eagle Outfitters',
  'american school of needle',
  'american weigh',
  'american weigh scales',
  'american weigh scales inc.',
  'American Weigh Scales, Inc.',
  'American Welding Society',
  'americana international',
  'Americana International Ltd.',
  'americas drive in corp. / sonic corp. amp; subsidiaries',
  'americas drive-in corp',
  'Americas Drive-In Corp. / Sonic Corp. & Subsidiaries',
  'amiclubwear',
  'Amiclubwear.com',
  'aminexil',
  'ammex',
  'Ammo',
  'Ammodor, LLC',
  'Ammunition',
  'amope',
  'AMOSTING',
  'ampeg',
  'AmScope',
  'amway',
  'amway corporation',
  'Amway Corporation (US)',
  'amybug #039;s attic',
  'Amybug\'s Attic',
  'amybugs primitive attic',
  'amzdeal',
  'AnalogMan Guitar Effects',
  'ancient nutrition',
  'Andrew James Worldwide',
  'Andy Thomas',
  'aneros',
  'Angela LaFramboise',
  'Angelynn',
  'angularizer',
  'anker',
  'ann cooper',
  'ann summers',
  'Annenberg Media',
  'annette haydon',
  'anolon',
  'ansonia records',
  'ansonia records inc.',
  'Ansonia Records, Inc.',
  'ansr',
  'AntennaX',
  'anviker',
  'Anvil Forge Art',
  'apara',
  'Apex Tool Group',
  'Apple',
  'apple watch band',
  'AQUALIBRA UK',
  'ar15',
  'AR15.com',
  'arancinotto',
  'arbitron global',
  'arburetor adjustment tool',
  'arc\'teryx',
  'ArcSoft',
  'Arctic Air Ultra',
  'Arduino, LLC',
  'ares',
  'ariel',
  'ariix llc',
  'ARIIX, LLC',
  'arilux',
  'arion',
  'Arm\'s Reach',
  'armani',
  'armorsuit',
  'artbeats software',
  'artbeats software inc.',
  'Artbeats Software, Inc.',
  'articlings',
  'artis',
  'artnaturals',
  'Arturia',
  'as seen',
  'Ashleigh Talbot',
  'ashley black\'s fasciayoga',
  'ashley diana black international holdings',
  'ashley electric',
  'ashomie',
  'asimoon',
  'asin:b01hslsotc, b01n2gw4ty',
  'AsKoruBeads',
  'astatic',
  'astro pneumatic tool',
  'at-a-glance',
  'atlantic research and mar',
  'Atlantic Research and Marketing (A.R.M.S.)',
  'atlantic research and marketing a.r.m.s.',
  'atomic beam usa',
  'Atvimports',
  'au ntic brands group llc',
  'audio technica',
  'auntie anne',
  'auntie anne #039;s inc.',
  'Auntie Anne\'s, Inc.',
  'aussie',
  'austin city limits',
  'Austin City Limits/KLRU',
  'australian gold',
  'australian gold inc.',
  'Australian Gold, Inc.',
  'Australian Made Campaign Limited',
  'authentic brands group ll',
  'Authentic Brands Group LLC',
  'autism speaks',
  'autism speaks inc.',
  'Autism Speaks, Inc.',
  'auto meter products inc. autometer',
  'Auto Meter Products, Inc. (Autometer)',
  'Autodata Limited',
  'Autoline Industries',
  'automotive technologies',
  'automotive technologies inc.',
  'Automotive Technologies, Inc.',
  'AutoWin.Eu LTD',
  'avedis zildjian',
  'avedis zildjian co.',
  'Avedis Zildjian, Co.',
  'axion',
  'B. C. Broncos',
  'b.h.p.',
  'b.h.p. inc. dba nialaya jewelry',
  'B.H.P., Inc. dba Nialaya Jewelry',
  'b.k.licht',
  'B&M Racing',
  'b00denv72k',
  'b01mueuxtw',
  'b06xg3248k',
  'b06xwkmd4r',
  'b0734v2dpm',
  'babe lash',
  'babe lash eyelash serum',
  'baby and brooke',
  'baby banana',
  'baby einstein',
  'Baby K\'tan',
  'babyliss',
  'babyliss for men',
  'bad boy',
  'Bad Monkey Productions',
  'bafx',
  'baire bottles',
  'BaKblade',
  'Baldwin',
  'balega',
  'Bally Pinball Fun',
  'balm cosmetics',
  'barda',
  'bare essentials',
  'barello uk',
  'bark outfitters',
  'barkoutfitters',
  'barnett research and comp',
  'Barnett Research and Computer Imaging',
  'barrettine',
  'barska',
  'Barstool Sports, Inc.',
  'barvivo',
  'basilica botanica',
  'Baume & Mercier',
  'baume amp; mercier',
  'baxter',
  'bazooka',
  'Beach Body',
  'BeachBody',
  'beachbody llc',
  'Beachbody, LLC',
  'beakey',
  'bean bag bazaar',
  'Bear Grylls Ventures LLP',
  'bearded ben',
  'beardeur',
  'beautiful beanbags',
  'beautiful beanbags limited',
  'beauty junkees',
  'beautycc',
  'Bed Band Store',
  'bedtime pal',
  'been5le',
  'bekilole',
  'BELDT Labs',
  'Belkin',
  'bell',
  'bell helicopter textron',
  'Bell Helicopter Textron Inc.',
  'bella scarf',
  'bellefit',
  'bellefit, inc,',
  'BEMER Int. AG',
  'Ben Kaufman Sales Co.',
  'Benchmade',
  'benchmade knife company',
  'benchmade knife company inc.',
  'Benchmade Knife Company, Inc.',
  'benefiber',
  'beretta',
  'Beverly Hills MD',
  'Beyond Cell',
  'BG Soflex, LLC',
  'bicol',
  'Big Boss',
  'big mouth',
  'big pictures',
  'bigmouth',
  'bigmouth inc',
  'Bill Lawrence Products',
  'bill owen cowboy artist',
  'Bill Owen-Cowboy Artist',
  'billie w. taylor ii',
  'billie w. taylor ii ph.d.',
  'Billie W. Taylor II, Ph.D.',
  'billionaire healthcare',
  'bino products llc',
  'BINO Products, LLC',
  'Biomic Sciences, LLC',
  'biosun',
  'Biotrade Bulgaria Ltd.',
  'BioTrust Nutrition',
  'birkin',
  'birkin shoulder',
  'bissell',
  'BISSELL Homecare, Inc.',
  'Bittrex, Inc.',
  'Black & Decker',
  'BLACK + DECKER',
  'Black and Decker',
  'Black Decker',
  'Black,Decker',
  'Black+Decker',
  'blackpoint engineering',
  'blackpoint engineering llc',
  'Blackpoint Engineering, LLC',
  'blankietails',
  'blaster',
  'blaster oil',
  'blastersquad',
  'blaupunkt',
  'blazebox',
  'Blitzburgh Sports',
  'blitzwolf',
  'blockware llc d.b.a. great useful stuff',
  'Blockware, LLC dba Great Useful Stuff',
  'bloomberg',
  'Bloomberg L.P.',
  'blooming bath',
  'BlossomSugarArt',
  'Blowgun',
  'blue gentian',
  'blue gentian, llc',
  'blue ribbon book',
  'bob',
  'Boba',
  'body sculpture',
  'bodyorbit',
  'bodysocks',
  'boldloft',
  'bolide',
  'Bombardier Recreational Products, Inc.',
  'bon aire',
  'bonnie #039;s plants',
  'Bonnie\'s Plants',
  'bonnies plants',
  'boosteady',
  'boppy company',
  'Boppy Company, The',
  'bosch',
  'Bose',
  'Bose Corporation',
  'Botanissa LLC - See U Baby',
  'bouch',
  'bouffe',
  'Bounce',
  'bounce for beginners',
  'Bounty',
  'Boveda, Inc.',
  'bowflex',
  'Bowl Light',
  'boyko',
  'braketeer',
  'Bramble',
  'Braniff Airways, Incorporated.',
  'Braun',
  'braven',
  'Breathe Easy',
  'Brenda Franklin',
  'breville',
  'Brian Smith',
  'Bridgestone Brands, LLC',
  'brightech',
  'Brisant Secure Ltd',
  'britelites',
  'british american innovations',
  'british phonographic indu',
  'British Phonographic Industry Limited',
  'broadway',
  'Broadway Basketeers',
  'Bronze Gallery',
  'brooklyn brownie',
  'brother',
  'Brother International',
  'Brother Toner Cartridge',
  'brown bear',
  'browning laboratories',
  'browning laboratories inc.',
  'Browning Laboratories, Inc.',
  'Bruce Lee Enterprises',
  'brush hero',
  'brushhero',
  'brutus',
  'bryo llc',
  'bsa',
  'btw enterprises',
  'bua',
  'bua inc.',
  'Bua, Inc.',
  'bubble wrap',
  'Buck Knives, Inc.',
  'bug me video',
  'Bug Me Video Inc.',
  'bulbhead',
  'bullet',
  'Bumbleride',
  'Bumbleride Inc.',
  'Bumkins Finer Baby Products',
  'Burberry Limited',
  'burei',
  'burlen fuel system',
  'Burlen Fuel System Limited',
  'burn hd',
  'burris',
  'bushnell',
  'bushnell performance opti',
  'Bushnell Performance Optics and Tasco Sales Pty Ltd.',
  'business software allianc',
  'Business Software Alliance (EU)',
  'buy decorative film',
  'buydecorativefilm',
  'Bwthynbach',
  'by california basics',
  'by matcha 108',
  'cabalicol',
  'Cabeau',
  'cable matters',
  'cacuss',
  'cadeau@t-online.de',
  'california basics',
  'california home goods',
  'calutech',
  'calutech inc.',
  'Calutech, Inc.',
  'camco',
  'cameraquest',
  'can\'t live without it, inc',
  'can\'t live without it, inc.',
  'canadian standards associ',
  'Canadian Standards Association',
  'canon',
  'canon inc.',
  'Canon, Inc.',
  'canyon chenille',
  'canyon chenille inc.',
  'Canyon Chenille, Inc.',
  'canyon dancer motorcycle',
  'Canyon Dancer Motorcycle Products',
  'capt_nemo',
  'captainki',
  'car cane',
  'car freshner corporation',
  'Car Scenter Electric Diffuser',
  'car seat footrest',
  'Car-Freshner Corporation',
  'carabas',
  'carbine',
  'carbocage',
  'carbocage keycage',
  'carburetor adjusting tool kit',
  'carburetor adjustment tool',
  'carchain',
  'card boy',
  'Cards Against Humanity',
  'care creations',
  'care creations inc.',
  'Care Creations, Inc.',
  'carelax',
  'carino',
  'carino healthcare',
  'carista',
  'carl mccoy',
  'Carl McCoy (Fields of the Nephilim)',
  'Carleon',
  'Carlstar Group – ITP and Carlisle Brands',
  'Carlstar Group â€“ ITP and Carlisle Brands',
  'carmen #039;s vintage collections',
  'Carmen\'s Vintage Collections',
  'carmens vintage collecti',
  'carmix gps',
  'Carmix-GPS',
  'carol ann clarke',
  'carrera',
  'carrimi',
  'carrs coins and rocks',
  'carrs coins and rocks inc.',
  'Carrs Coins and Rocks, Inc.',
  'carters',
  'Cartier',
  'Cascade',
  'case-mate',
  'caseology',
  'casio',
  'catenina',
  'cath kidston',
  'caths pennies designs',
  'catit',
  'cbd',
  'cbs entertainment',
  'cbs entertainment and desilu too llc unforgettable licensing',
  'CBS Entertainment and Desilu, too, LLC (Unforgettable Licensing)',
  'CBT Nuggets, Inc',
  'CDF Firefighters / CAL FIRE Local 2881',
  'cedar brands',
  'cees',
  'Celebrate Vitamins',
  'celebration bar review',
  'celluliteblaster',
  'centaure',
  'Centerforce',
  'ceranet',
  'ceranet inc.',
  'CeraNet, Inc.',
  'cfsds',
  'chalk & vermilion fine ar',
  'Chalk & Vermilion Fine Arts',
  'chalk amp; vermilion fine arts',
  'chalkboard',
  'chalktalk sports',
  'Chandler Tool',
  'chanel',
  'chanel inc.',
  'Chanel, Inc.',
  'charisma brands, llc',
  'Charizard',
  'Charles Cook',
  'Charmed Creations LLC',
  'Charmin',
  'Chaz Dean Studio',
  'Chazpro',
  'cheer',
  'chemical guys',
  'chemo cap',
  'Chemsavers, Inc.',
  'cher-ished treasures',
  'Chevron Corporation',
  'chief architect',
  'chief architect inc.',
  'Chief Architect, Inc.',
  'chill gorilla',
  'ChloÃ©',
  'chloe',
  'Chloé',
  'Chocolate Starfish Ltd.',
  'chocolate starfish.',
  'Choon\'s Design',
  'Chubby Chico Charms LLC',
  'circulon',
  'Cisco-Linksys',
  'citric acid',
  'cityback',
  'clairol',
  'clarins',
  'clarisonic',
  'Classic Ultrasonic Aromatherapy Diffuser',
  'classic video',
  'classic video l.l.c.',
  'classic-video',
  'classical realism',
  'clay in motion',
  'Clayful Creations',
  'Clearblue',
  'cleenbo',
  'clipart design usa',
  'Cloanto IT srl',
  'cloanto italia',
  'cloanto italia srl',
  'CLOCHE COUTURE TRADEMARK',
  'clog remover',
  'closet complete',
  'clou de selle',
  'cloud b inc.',
  'Cloud B, Inc.',
  'cloud nine',
  'clouds',
  'clr',
  'club petz',
  'coach',
  'coach inc.',
  'Coach, Inc.',
  'cobra',
  'cobra radio',
  'cobrabraid',
  'cocktailier',
  'Cocktailier LLC',
  'cocktailier, llc',
  'cokaka',
  'colart americas',
  'colart americas inc.',
  'ColArt Americas, Inc.',
  'coldwater creek',
  'Coldwater Creek Inc.',
  'Collar and Cuffs London',
  'colnago',
  'Colnago America, Inc.',
  'ColorMetrics LLC/ HairMarker LLC',
  'Columbia',
  'com-four',
  'com-four vertriebs gmbh',
  'ComitÃ© Champagne',
  'ComitÃ© Georges Mathieu',
  'Comité Champagne',
  'Comité Georges Mathieu',
  'command arms',
  'compare to avery 51',
  'Competition Clutch',
  'conair',
  'Confederate Motorcycles LLC',
  'constance',
  'Continental Airlines',
  'Continental Enterprises',
  'controlomatic',
  'converse',
  'coobey',
  'cool mobility',
  'Cool Mobility - Johanson Nominees Pty.',
  'cool mobility johanson nominees pty.',
  'coosa',
  'Coquetry Clubwear',
  'CORE Survival, Inc.',
  'Corian',
  'cosanti originals',
  'Cosanti Originals by Paolo Soleri',
  'cosmetics',
  'cosmic debris',
  'Country Collectibles',
  'coway',
  'coway co. ltd',
  'Coway Co., Ltd',
  'Cozy Glow Ltd.',
  'Cozy Sack',
  'cpap',
  'Crabs Adjust Humidity',
  'Craft-e-Creations',
  'craftsman',
  'Cranberry Card Company',
  'cratsman',
  'Crazy Aaron\'s Puttyworld (Crazy Aaron\'s Thinking Putty)',
  'creations',
  'creative carvings',
  'Creative Carvings by Monte',
  'creative fitness',
  'creative technology ltd',
  'creatov',
  'Creature Comforts Ltd dba Cornwall Stoneware Co.',
  'Creeks End Crochet',
  'Crest',
  'criswell embroidery',
  'Criswell Embroidery & Design',
  'criswell embroidery amp; design',
  'Crochead Pty Ltd',
  'crochet crafts',
  'crocs',
  'crocs asia',
  'crocs inc.',
  'Crocs, Inc.',
  'crosman',
  'Crown Cookware',
  'cruzee',
  'Crystal Allies Gallery',
  'ctron21',
  'ctron21®',
  'ctybb',
  'cucusoft',
  'cucusoft inc.',
  'Cucusoft, Inc.',
  'cuddlebug',
  'cuisinart',
  'cuisinart sunbeam oster krups',
  'cuppa mix',
  'cutco cutlery',
  'Cutco Cutlery Corporation',
  'cutecolors',
  'Cutecolors.com',
  'cutting board bamboo extra juice groove large serving tray kitchen wood butcher',
  'Cynthia Dakin',
  'Cypress Collectibles',
  'Daimler',
  'Daimler AG',
  'Dais Enterprises',
  'damiando',
  'danes r us great dane amp; pet art',
  'danes-r-us great dane',
  'Danes-R-Us Great Dane & Pet Art',
  'daniel bingham',
  'Daniel Bingham Design Studio',
  'daniel wellington',
  'Danisco',
  'dansko',
  'dansko llc',
  'Dansko, LLC',
  'danworkshop',
  'Danworkshop.com',
  'DanziX',
  'dark horse comics',
  'dark horse comics inc.',
  'Dark Horse Comics, Inc.',
  'darkhorse ranch',
  'darkhorse ranch inc.',
  'DarkHorse Ranch, Inc.',
  'dasco pro',
  'dash america dba pearl izumi inc.',
  'Dash America dba Pearl Izumi, Inc.',
  'Dassault Systemes S.A.',
  'data professionals',
  'data-professionals',
  'datapro',
  'davaon',
  'dave #039;s discount motors',
  'Dave Fant Company Of Arkansas Inc',
  'Dave\'s Discount Motors',
  'daves discount motors',
  'David Barton',
  'Davidson Photography',
  'Dawn',
  'dazi',
  'DB Research L.L.P.',
  'dba',
  'dba 3 sprouts',
  'dba boricap',
  'dba chefs resource',
  'dba nialaya jewelry',
  'dba stella',
  'De\'Longhi',
  'de´ longhi',
  'debrief me',
  'decathlon',
  'deco express',
  'deco express®',
  'decowall',
  'Dedo Weigert Film GmbH',
  'deepline',
  'Deere',
  'degbit',
  'DeLaine\'s',
  'dell',
  'dell computer',
  'Dell Computer Corp.',
  'DeLonghi',
  'Delorean Motor Company',
  'Delphi Technologies',
  'delta air lines',
  'delta air lines inc.',
  'Delta Air Lines, Inc.',
  'deluxe',
  'deluxe aqua',
  'deluxe aqua lube',
  'deluxe body',
  'dental health essentials',
  'dental health essentials llc',
  'DermalMedix',
  'dermalogica',
  'dermalogica inc.',
  'Dermalogica, Inc.',
  'dermawand',
  'DESCO Corporation',
  'desilu',
  'DeWalt',
  'DFLK Inc.',
  'dhld',
  'dhpc inc',
  'diane',
  'dick harrell',
  'dick harrell performance',
  'Dick Harrell Performance Center, Inc. (\'DHPC Inc.\') Licensing Department',
  'diesel',
  'Diesel (London) Ltd.',
  'diesel london ltd.',
  'Diesel Zero',
  'diesel zero plus eau de toilette for men - 75 ml',
  'digital ant',
  'digital innovations',
  'digium inc.',
  'Digium, Inc.',
  'dihl',
  'Dingo',
  'Dinnages (1989)',
  'dionne quintuplets',
  'Dionne Quintuplets, The',
  'direct designs',
  'discount tens',
  'discounttens',
  'disney',
  'DMS International',
  'doctor #039;s associates inc. dba subway',
  'doctor drain',
  'Doctor\'s Associates Inc. dba Subway',
  'doctors associates',
  'Doggie Bow Ties',
  'dohomai',
  'dolby laboratories inc.',
  'Dolby Laboratories Inc. ("Dolby")',
  'Dollar Shave Club',
  'Don\'t Die, LLC',
  'Dongguan Hawson Jewelry',
  'donmar enterprises',
  'donmar enterprises inc. skyroof',
  'DONMAR Enterprises, Inc. - SKYROOF®',
  'DONMAR Enterprises, Inc. - SKYROOFÂ®',
  'donnerberg',
  'donnerberg®',
  'Dorco',
  'Doria International, Inc.',
  'dörrwerk',
  'doterra young living',
  'Downy',
  'DPCD',
  'dr beats',
  'dr. denese',
  'Dr. Denese - SkinScience Labs, Inc.',
  'dr. denese skinscience labs inc.',
  'dr. marten\'s',
  'Dr. Marty - Animal Ambassadors, LLC',
  'Dr. Natura',
  'Drageekiss Ltd.',
  'drain opener',
  'drain out',
  'drano',
  'Dre Beats',
  'dream like',
  'dream water',
  'Dreamline',
  'dreamwear and cpap',
  'dreamwork',
  'dreft',
  'drei schwerter',
  'dremel rotary tool',
  'dressthatman',
  'DressThatMan.com',
  'drive in exchange ltd',
  'drive medical',
  'drive-in exchange',
  'Drive-In Exchange, Ltd',
  'DrNatura',
  'dropcrate',
  'dropcrate llc',
  'DropCrate, LLC',
  'drumpf.wtf',
  'Dryer Balls',
  'dryfhout enterprises, llc dba bakblade',
  'dryguy',
  'Ds Lite',
  'Dsi Xl',
  'DSMB Partners, LLC DBA ActivatedYou',
  'DTX International',
  'duffel',
  'duke of pearl',
  'duke of pearl llc',
  'Duke of Pearl, LLC',
  'dumbbell',
  'Dunhill',
  'dunlop manufacturing',
  'dunlop manufacturing inc.',
  'Dunlop Manufacturing, Inc.',
  'duplo',
  'duracell',
  'Duracell U.S. Operations, Inc.',
  'durex pleasure ring',
  'Dust Daddy',
  'duvet',
  'dymatize',
  'dymatize enterprises, llc',
  'Dynamic Resource Group',
  'E. I. du Pont de Nemours and Company (DuPont)',
  'e. mishan & sons, inc',
  'e.i. du pont de nemours a',
  'E.I. du Pont de Nemours and Company',
  'Eagle Creek Enterprises - Tim Cox Fine Art',
  'eagle creek enterprises tim cox fine art',
  'eames office',
  'Eames Office - Lucia Eames',
  'eames office lucia eames',
  'easehold',
  'easewax',
  'Eason Media Ltd',
  'East Direct (UK) Ltd',
  'easton sports',
  'easton sports inc',
  'Easton Sports Inc.',
  'eccpp',
  'eccppautoparts',
  'echo',
  'echo dot',
  'eclipse records',
  'eclipse records inc',
  'Eclipse Records, Inc.',
  'eco4us',
  'EcoSphere',
  'ecosphere associates',
  'ecosphere associates inc.',
  'Ecosphere Associates, Inc.',
  'ecotools',
  'edenware',
  'edepotexpresscs',
  'edgar rice burroughs',
  'edgar rice burroughs inc.',
  'Edgar Rice Burroughs, Inc.',
  'EDGE PRODUCTS',
  'Edison Nation',
  'efbcs feline conservatio',
  'EFI Live Limited Co.',
  'egée',
  'egg sitter',
  'egyptian magic',
  'eiission',
  'eldaco',
  'electriduct inc',
  'electro harmonix effects',
  'Electro-Harmonix Effects',
  'electronic temperature instruments ltd',
  'elektroden pads',
  'elf stor',
  'ELK',
  'Ellison Educational Equipment, Inc. - Sizzix LLC',
  'ellura',
  'eloi',
  'Elope Inc.',
  'ematic',
  'Ember Candles',
  'emsoninc',
  'ENERGYbits Inc.',
  'enfagrow',
  'enfamil',
  'Environ Skin Care Pty Ltd',
  'epauto',
  'Epic Coolers',
  'epionce',
  'epson',
  'Epson (UK) Corporation',
  'epson america inc.',
  'epson america, inc.',
  'epson uk corporation',
  'era',
  'Ergo baby',
  'ergo baby carrier inc.',
  'Ergo Baby Carrier, Inc.',
  'Ergobaby',
  'ergobaby easy snug infant insert',
  'ergotopia',
  'erica skadsen',
  'Erica Skadsen/Organic',
  'es distributions llc',
  'ESA - Entertainment Software Association',
  'esc',
  'esc europe ltd',
  'esc ltd',
  'escort',
  'essential marine products',
  'estate of garry winogrand',
  'estate of marilyn monroe llc',
  'Etienne Aigner AG',
  'etrailer',
  'etrailer.com',
  'Eukanuba',
  'euphoria',
  'eurmax',
  'eurmax canopy, inc',
  'euro-pro',
  'Eurotech Photographics',
  'ev cables',
  'eventronic',
  'Ever Brite Ultra',
  'everlast',
  'excelvan',
  'Exel Products',
  'exeter research',
  'exoterra',
  'exploding kittens',
  'eyes of india',
  'EzyDog LLC',
  'f & f stores',
  'f?',
  'FÃ©dÃ©ration Internationale de Football Association (FIFA)',
  'Fab1Direct Ltd - Fablogix',
  'fabjob',
  'FabJob.com',
  'Fabriika',
  'faceblaster',
  'facelift',
  'facelift ent. inc',
  'Facelift Ent. Inc.',
  'faces of death',
  'fairwin',
  'farberware',
  'farmland',
  'farmland foods inc.',
  'Farmland Foods, Inc.',
  'fascia nation',
  'fasciablaster',
  'Fashion Polish',
  'fasmov',
  'Fast Eddie\'s Vape Shop and Lounge, LLC',
  'fat gripz',
  'fc bayern m?',
  'FC Bayern MÃ¼nchen',
  'FC Bayern München',
  'fca us llc',
  'FCA US, LLC',
  'Febreze',
  'federal express corporati',
  'Federal Express Corporation (FedEx)',
  'federal express corporation fedex',
  'federation against copyri',
  'federation against copyright ft fact ltd',
  'Federation Against Copyright Theft (FACT) Ltd',
  'Fédération Internationale de Football Association (FIFA)',
  'fedex',
  'fender musical instrument',
  'Fender Musical Instruments Corporation',
  'fening',
  'Ferret Company',
  'fgm ventures llc dba petpost',
  'FGM Ventures, LLC dba Petpost',
  'fh group',
  'Fields',
  'fields of the nephilim',
  'fifa',
  'filemaker',
  'filemaker inc.',
  'FileMaker, Inc.',
  'fintie',
  'Fire Cam',
  'Fire House Neon LLC',
  'Firearm',
  'first force',
  'first great western',
  'first group',
  'First Group / First Great Western',
  'Fishman',
  'fiskars',
  'Fit and Glow Inc.',
  'fitbit',
  'fitbit alta',
  'fitbit blaze charger',
  'fitdeck',
  'fitness anywhere',
  'fitness brands',
  'Fitness Brands Inc. / Direct Entertainment Media Group',
  'fitness brands inc./direct entertainment media group',
  'FJA Mods',
  'fjerry',
  'Fjerry, LLC dba What Do You Meme, LLC',
  'Flare',
  'fleurville florida',
  'fleurville florida council of bromeliad societies inc.',
  'Fleurville Florida Council of Bromeliad Societies, Inc.',
  'flex seal',
  'flex tape',
  'Flexibrace',
  'flipside wallets',
  'Flowmaster',
  'Fluidity Enterprises, Inc.',
  'fluval',
  'focus t25',
  'focuspet',
  'foodvacbags',
  'fooing',
  'footprints publishings in',
  'Footprints Publishings Inc.',
  'ford motor',
  'Ford Motor Company',
  'foreo',
  'foreo ltd.',
  'foreo luna',
  'Forever 21',
  'forliver',
  'formufit',
  'FORMUFIT LLC',
  'Fort Worth Stock Show & Rodeo',
  'forum novelties',
  'foscam intelligent',
  'foscam intelligent technology co. ltd.',
  'Foscam Intelligent Technology Co., Ltd.',
  'Foshan Shunde Shines E-Commerce Co., Ltd',
  'fossil',
  'fossil inc.',
  'Fossil Reproductions',
  'Fossil, Inc.',
  'fourbi',
  'FourGreen Auto Parts',
  'Fox (Twentieth Century Fox Film Corporation)',
  'fox twentieth century fox film corporation',
  'Frantic Stamper, Inc.',
  'freebit',
  'Fretless Finger Guides',
  'frito lay inc.',
  'frito-lay',
  'Frito-Lay, Inc.',
  'frontline',
  'frozen dessert',
  'frozen dessert supplies',
  'Frux',
  'frux home and yard',
  'fuelbelt',
  'fuji natural',
  'fujifilm',
  'Fujikura Composites',
  'fulvio bianconi',
  'funace',
  'funding',
  'Funding USA LLC',
  'FURminator',
  'Furniture Feet',
  'fuze chicken',
  'fyshflyer',
  'g. loomis inc.',
  'G. Loomis, Inc.',
  'gablemere',
  'gablemere ltd',
  'gaiam',
  'gaiam inc.',
  'Gaiam, Inc.',
  'Gain',
  'Galiva Inc.',
  'Games 4 Hens Ltd',
  'Garden Selections Ltd.',
  'gardspo',
  'garmin',
  'Garmin (UK)',
  'garnier',
  'Garry Winogrand Photography',
  'gas block',
  'gaylord',
  'Gaylord Entertainment Company',
  'gear4',
  'gear4 hk limited',
  'gemstone',
  'General Motors',
  'generic',
  'Geneva Laboratories Ltd',
  'genius gmbh',
  'genuine by eiission',
  'George Foreman',
  'george halbert production',
  'georgia pacific',
  'Georgia Pacific Corp.',
  'georgie girl',
  'Georgie Girl Australia',
  'Gerber',
  'gerber childrenswear',
  'gerber childrenswear llc',
  'Gerber Childrenswear, LLC',
  'geri-sleeve',
  'Getonfleek',
  'gex',
  'gex worldwide',
  'ghb',
  'ghome',
  'Giant UK LTD',
  'gibson',
  'gibson brands inc.',
  'gibson brands, inc',
  'Gibson Brands, Inc.',
  'gibson guitar corp',
  'Gibson Performance Exhaust',
  'Gilette Venus',
  'Gillette',
  'giraffe',
  'Giraffe Bath & Body, LLC',
  'giro',
  'giro launch',
  'gkhair',
  'glass of vennice',
  'Glenns Auto Repair and Performance LLC dba Glenns Auto Performance',
  'Global Healing Center',
  'global-keratin',
  'GloFish',
  'glovework',
  'GMV Productions',
  'gn netcom',
  'gn netcom dba jabra',
  'GN Netcom, dba Jabra',
  'Go Girl',
  'Go Nutrients',
  'go-ped',
  'Goal Zero',
  'Goetze\'s Candy',
  'GoGirl',
  'Goja',
  'goliath',
  'gomoji',
  'goo baby',
  'good news',
  'Gopher',
  'gopro',
  'Gorilla Tech LTD',
  'gotham steel',
  'gottlieb development llc',
  'Gottlieb Development, LLC',
  'gourmeo',
  'GQ Electronics',
  'graco',
  'graco inc',
  'grand chapter of phi sigm',
  'grand chapter of phi sigma kappa inc.',
  'Grand Chapter of Phi Sigma Kappa, Inc.',
  'grand lodge fraternal ord',
  'Grand Lodge Fraternal Order of Police',
  'grandma moses properties',
  'Grandma Moses Properties Company',
  'Graphics Technology HK Limited',
  'Graphite Design, Inc.',
  'Gratiae',
  'Graydog Woodenware',
  'Great Bay Home',
  'great healthworks',
  'GREAT STUFF',
  'green bracket',
  'greenhurst',
  'Grenadine Apparel',
  'grenadine apparel inc',
  'grenco science inc.',
  'Gretsch Company',
  'grill beast',
  'grill griddles',
  'grillaholics',
  'GrimmSpeed',
  'Grizzly',
  'grohe',
  'Grover',
  'grundig',
  'grupo rs',
  'GU Original',
  'guaranty',
  'guess and marciano',
  'GUESS and MARCIANO Brands',
  'Gundry MD',
  'gunnar optiks llc',
  'GUNNAR Optiks, LLC',
  'gusti',
  'guthy renker corporation',
  'guthy-renker',
  'Guthy-Renker Corporation',
  'gymworld',
  'h d\'ancre',
  'h hermessence collection brin de réglisse',
  'h n e w s',
  'h&b',
  'H&M',
  'h2o',
  'habor',
  'hagen',
  'Hair Flair LTD',
  'Hair Food',
  'hairy rs',
  'halio',
  'Hamilton Beach',
  'hamilton housewares',
  'hanayama puzzles of japan',
  'hands free magnetic screen door',
  'Handy Brite',
  'Handy Heater',
  'hane',
  'hangerworld',
  'harbinger',
  'hario',
  'harley davidson motor company',
  'harley-davidson',
  'Harley-Davidson Motor Company',
  'harmon',
  'hartley loudspeakers',
  'hartley loudspeakers inc.',
  'Hartley Loudspeakers,Inc.',
  'hasbro',
  'hausbell',
  'hcctoo',
  'hdmi licensing',
  'hdmi licensing llc',
  'HDMI Licensing, LLC',
  'Head & Shoulders',
  'Heirs and Estate of Peter William Ham',
  'helena lind',
  'helga',
  'hells angels motorcycle',
  'Hells Angels Motorcycle Corporation Italia',
  'hemp',
  'hemptouch',
  'hepheas',
  'Herbal Essences',
  'herbalife',
  'hermes',
  'hermes editeur',
  'herschel',
  'Herschel Supply Company Ltd.',
  'hewlett packard company hp ink amp; toner',
  'Hewlett-Packard',
  'Hewlett-Packard Company (HP Ink & Toner)',
  'hexin',
  'hi-bagz',
  'HIDS4U®',
  'HIDS4UÂ®',
  'high island health',
  'High Island Health, LLC dba Aneros',
  'higher nature',
  'Hillstock Collection',
  'Himalaya Drug Company',
  'HISMILE',
  'hitchmate',
  'HK Wuppertal-Solingen-Remscheid',
  'HKS Europe Ltd',
  'Hoberman Designs',
  'hogue',
  'hollywood racks',
  'home power',
  'home power inc.',
  'Home Power, Inc.',
  'homecube',
  'homekey',
  'homeopathy world',
  'hompo',
  'honb',
  'honeycat',
  'Hong Kong Proster Trading Limited',
  'hooai',
  'hook and loop tape roll strips with adhesive back mounting tape for picture and tools hanging pedal board fastening by jiho',
  'hook-eze',
  'Hook-Eze Pty Ltd',
  'Hoover',
  'horizon hobby',
  'horizon hobby inc.',
  'Horizon Hobby, Inc.',
  'HotBuckles',
  'hounds to humans',
  'HouseLabels.com',
  'HP',
  'hsl',
  'Hubmar',
  'huele',
  'huggalugs',
  'Huggalugs North America',
  'Huggaroo',
  'Huggle Hoodie',
  'Huggle Pets',
  'Huggle Socks',
  'Hugs Not Drugs',
  'human touch',
  'human touch llc',
  'Human Touch, LLC',
  'humble chic ny',
  'hunter',
  'Hurri Clean',
  'hurricane',
  'hurricane spin',
  'Husky Liners',
  'Hy Cite Corporation',
  'hybrid systems',
  'hybrid systems ltd. inc. hsl',
  'Hybrid Systems Ltd., Inc. (HSL)',
  'Hydor Group',
  'hydro gizmos',
  'hydroluxe',
  'Hypertech',
  'i-unik',
  'i2x',
  'IAMS',
  'icetrekkers',
  'iclever',
  'id films',
  'idash',
  'Ideal Industries',
  'IE WORKS, LLC',
  'iFixit',
  'igeress',
  'ikea',
  'illico',
  'Illume Holding Company LLC',
  'image skincare',
  'Image Vital C',
  'imex',
  'implus',
  'in-a-bag',
  'incipio',
  'incipio technologies inc.',
  'Incipio Technologies, Inc.',
  'indian arts',
  'Induction Innovations',
  'industrie und handelskamm',
  'Infinite Prosperity USA, LLC - Bluesky Travel Group Pty Ltd',
  'inflatablesgiant',
  'inglesina',
  'Inline Tube, Inc.',
  'innoo tech',
  'Innovative JK Products LLC',
  'Innovative Salon Products, Inc. (LOMA)',
  'Innovative Textiles Inc.',
  'innovo',
  'innovo deluxe',
  'insanity workout',
  'Insert Knowledge Here',
  'instant power',
  'InStyler',
  'instyler max',
  'Intenze',
  'International Commercial Television - ICTV Brands',
  'international watchman',
  'intex',
  'intuit',
  'intuit inc.',
  'Intuit, Inc.',
  'invisible dog fence',
  'inVitamin, LLC',
  'iOS',
  'iottie',
  'ip holdings',
  'ipad',
  'iphone',
  'ipow',
  'ipow easy one touch mini',
  'iprotect',
  'iprotect®',
  'IQ Implant Devices',
  'IQAir',
  'iris',
  'iRobot',
  'iRobot Corporation',
  'Iron Gym',
  'IronMind Enterprises, Inc.',
  'isle surf and sup',
  'iso beauty',
  'ISW Trading Pty. Ltd.',
  'it works marketing compli',
  'It Works Marketing Compliance',
  'ivory',
  'Ivory Snow',
  'jabra',
  'jack sealey',
  'jack sealey ltd',
  'jacket4bikes',
  'jackets4bikes',
  'Jaclin Dunne',
  'jaguar',
  'Jaguar & Land Rover',
  'jaimie jacobs',
  'James Andrew Grant',
  'james bond',
  'jayco',
  'Jayco (UK) Limited',
  'jbl',
  'jdmspeed',
  'jeannine',
  'JEDirect Corp dba JETech Design',
  'Jemella Ltd',
  'jenga',
  'jenga game',
  'Jenni Leigh Creations',
  'jet performance products',
  'jet performance products inc',
  'Jet Performance Products, Inc',
  'jetech',
  'jetechdesign',
  'Jewelry Organizer',
  'Jeweltailor Ltd.',
  'jewelultradiamondbrite',
  'Jim Pace Magic',
  'JMDL Toys',
  'jmitoo',
  'jml',
  'jml ltd',
  'JNimports Ltd. dba Periea',
  'Jo Condrill',
  'joe foreman',
  'johanson nominees',
  'John Deere',
  'john mills limited',
  'joking hazard',
  'joking hazard llc',
  'jonsnow',
  'jordan',
  'Jordan Design',
  'jordan design studio',
  'Joseph Rorie',
  'joy',
  'joy baby',
  'joy celebrations',
  'joy kroeger beckner',
  'joy kroeger beckner classical realism from hounds to humans',
  'Joy Kroeger Beckner, Classical Realism, from Hounds to Humans',
  'joyfay',
  'joyfay®',
  'JRM Licensing',
  'js amp;m sales amp; marketing inc.',
  'JS&M Sales & Marketing Inc.',
  'jtrim',
  'JTY Imports/Exports Pty Ltd',
  'Juul, Inc.',
  'JuveTress',
  'jypsiere',
  'k.w. muth',
  'k.w. muth company inc.',
  'K.W. Muth Company, Inc.',
  'K&M International, Inc. - Wild Republic',
  'K&N',
  'k&s artisan',
  'kai z feng',
  'Kai Z Feng Limited',
  'kalita',
  'Kando Pictures Limited',
  'kapmore',
  'kari-me',
  'Kason Industries',
  'Kate Spade & Company',
  'kate spade amp; company',
  'kattee',
  'kayiwa limited',
  'kaz',
  'kaze',
  'KBA Enterprises LLC - Alban',
  'ke health llc',
  'KE Health LLC, DBA BoriCap',
  'kelly shoulder',
  'kellybag',
  'Kendama USA',
  'Kenrico Ltd.',
  'kensie',
  'kent displays',
  'kenu inc.',
  'Kenu, Inc.',
  'KENVELO',
  'KeraFiber Europe Limited',
  'kerastase',
  'Ketosource Ltd.',
  'kettle foods',
  'Kettle Foods Ltd',
  'Kevlar',
  'keysmart',
  'Kicker',
  'kictero',
  'Kikka Digga',
  'Kimberly-Carr',
  'kinetic sand',
  'King Baby Studio',
  'king technology',
  'king technology inc.',
  'King Technology, Inc.',
  'KiniArt Studios',
  'kitchen aid',
  'kitchenaid',
  'kk music store',
  'Klaire Labs',
  'Klasvsa (Huixian Dakang Electronic Commerce Co., Ltd.)',
  'klebeshop24',
  'Kleinn',
  'kleinn automotive accesso',
  'Kleinn Automotive Accessories',
  'klipsch',
  'klru',
  'kneeguardkids',
  'knive',
  'knives',
  'knowledge in motion inc.',
  'Knowledge In Motion, Inc.',
  'kodi',
  'kohbi-inc',
  'konikit',
  'KontrolFreek',
  'kopylot',
  'kronemann',
  'Kronemann Design Studio Pty. Ltd. - House of Kronemann USA',
  'kronemann design studio pty. ltd. house of kronemann usa',
  'kronenburg',
  'kronify',
  'kronify ®',
  'kronify®',
  'kt magic',
  'ktm',
  'kulkea',
  'Kun Shoulder Rest',
  'Kwikset',
  'kwmobile',
  'Kyser',
  'l-r-g',
  'l\'oreal',
  'l\'oreal s.a.',
  'La Boutique de Bacchus',
  'la chemise',
  'La Chemise Lacoste SA',
  'la muscle',
  'la ren',
  'lacoste',
  'lad hermes',
  'lady makeup',
  'lakeland',
  'lamaze',
  'lamphus',
  'land rover',
  'langley productions',
  'langley productions inc.',
  'Langley Productions, Inc.',
  'laphroaig',
  'larry hartsell',
  'larry hartsell seminars inc.',
  'Larry Hartsell Seminars, Inc.',
  'las vegas wranglers',
  'Las Vegas Wranglers Professional Hockey Team',
  'laser design',
  'laser design int #039;l llc',
  'Laser Design Int\'l, LLC',
  'latupo',
  'Law Enforcement',
  'Lay-n-Go, LLC',
  'LCR Health',
  'le creuset',
  'learherman',
  'learn yoga at home',
  'leatherman',
  'lebra',
  'LEDGLOW',
  'lego',
  'lelo',
  'lelo - leloi ab.',
  'lelong',
  'lenny and eva',
  'lenny and eva inc.',
  'Lenny and Eva, Inc.',
  'lenovo',
  'lenox',
  'les ailes d\'hermes',
  'letmy',
  'LetterRip Decals',
  'leupold & stevens',
  'Leupold & Stevens, Inc.',
  'leupold amp; stevens inc.',
  'Level Terrain LLC dba FlipBelt',
  'Levi Strauss & Co.',
  'levi strauss amp; co.',
  'levivo',
  'levivo pet',
  'Lexmark International Inc.',
  'lg lt700p',
  'Lia Sophia Jewelery',
  'Liberta Co., Ltd. dba Baby Foot USA',
  'liberty imports',
  'lifeproof',
  'LifeProof - Treefrog',
  'lifeproof treefrog',
  'lifetek',
  'lifetrons',
  'Lifetrons Switzerland GmbH',
  'LifeVantage',
  'lift',
  'lifted research group',
  'Lifted Research Group Inc. (L-R-G)',
  'lifted research group inc. l r g',
  'Light & Dark Productions',
  'light amp; dark productions',
  'lightning',
  'lights4fun',
  'lihao',
  'lilbetter',
  'lillian ruff',
  'lily\'s lights llc',
  'limuwa',
  'Linda McSweeney',
  'linkedin',
  'LinkedIn Corporation',
  'Linksys',
  'lion mane dog costume',
  'Lionsgate',
  'lionsmen',
  'lip ink',
  'Lip Ink® International',
  'Lip InkÂ® International',
  'lipo-6',
  'lipsy',
  'Lipsy Ltd',
  'liquid plumr',
  'liquid-plumr',
  'little hotties',
  'live and sleep',
  'live and sleep, llc (dba resort sleep)',
  'Live Cell Research',
  'liwacs',
  'llc dba adb interests',
  'llc dba sunlight supply,',
  'Lomo Industries Ltd.',
  'lone cone',
  'Longchamp',
  'loreal',
  'Lori G Ashley',
  'loveblue',
  'lucia eames',
  'luckies of london',
  'luckies of london ltd',
  'lumentics',
  'lumunu',
  'lumunu deluxe',
  'lumunu passion products',
  'LunchBots',
  'lure cupping',
  'lure essentials',
  'luvs',
  'luvvit',
  'luxe jewels',
  'luxe jewels llc dba stella amp; dot',
  'Luxe Jewels, LLC dba Stella & Dot',
  'Luxe Purses',
  'LuxeAvant Innovations',
  'luxottica group',
  'luxottica retail',
  'luxsego',
  'lynda',
  'lynn r. papercrafts',
  'm2 distribution ltd',
  'mackie',
  'MacNeil',
  'macOS',
  'mad about organics',
  'mad dogg athletics',
  'mad dogg athletics inc.',
  'Mad Dogg Athletics, Inc.',
  'magformers',
  'Magic Bullet',
  'magic bullet nutribullet',
  'magic bullet party bullet',
  'Magic Pad',
  'Magic Tracks',
  'Magmatic',
  'Magnet Shop',
  'Magnetic Poetry',
  'Magnolia Rubberstamps',
  'Makaton Charity',
  'make fascia great again',
  'make-u-think',
  'make-u-think, inc. dba truro games',
  'maketheone',
  'makita',
  'mamiya america corporatio',
  'Mamiya America Corporation',
  'Manchester United',
  'Manfrotto',
  'Manhattan Toy Company',
  'Mannatech Incorporated',
  'marianne #039;s sol mate socks inc.',
  'Marianne\'s Sol Mate Socks, Inc.',
  'marilyn monroe',
  'Marineland',
  'Market Muncher LLC - Home Intuition',
  'marljohns',
  'mars',
  'mars inc.',
  'Mars, Inc.',
  'marshal black',
  'marvel',
  'Mary Capan',
  'masonicbuy',
  'masta plasta limited',
  'master of illusions enter',
  'Master of Illusions Entertainment',
  'masterark',
  'matcha',
  'matcha 108',
  'mato & hash',
  'mato hash',
  'Matt Groening',
  'matty\'s mix-up',
  'matty\'s toy stop',
  'Mavala',
  'Mavala International',
  'maven',
  'maximal power',
  'maxxdry',
  'maxxima',
  'McCain Photography',
  'McDavid',
  'McGregor Fashion Group NV',
  'mDesign',
  'meal prep haven 3',
  'meco',
  'mecolletion',
  'medcosouth',
  'medcosouth healthcare',
  'medcosouth healthcare llc',
  'Medcosouth Healthcare, LLC',
  'mederma',
  'Medieval Moccasins',
  'medline',
  'meika',
  'meika ltd',
  'Melaleuca',
  'meland',
  'melissa & doug',
  'mellanni',
  'Mellotron Archives',
  'Melville Direct, LLC dba Bits and Pieces',
  'mendini',
  'meprolight',
  'Mercantile Station 2',
  'merle norman cosmetics',
  'merle norman cosmetics inc.',
  'Merle Norman Cosmetics, Inc.',
  'Metamucil',
  'Metropolitan Kitchen',
  'meyer',
  'MFi-Certified',
  'MGA Entertainment, Inc. - A.B.C. International',
  'Michael Kors',
  'michelles scrapbooking',
  'Micro Mechanic',
  'microplane',
  'Microsoft',
  'mier',
  'Might Sight',
  'Mighty Sight',
  'mike barrett',
  'Mike Barrett Productions Ltd.',
  'Mikimoto America',
  'millet',
  'Milwaukee',
  'milwaukkee',
  'minecraft',
  'Minelab Electronics',
  'Miniclip SA',
  'Ministero delle politiche agricole — ICQRF',
  'Ministero delle politiche agricole â€” ICQRF',
  'Ministry of Defense',
  'Miracle Bamboo Bra',
  'Miracle Bamboo Cushion',
  'Miracle Bamboo Pillow',
  'Miracle Of Aloe',
  'Miracle Socks',
  'Miraflex S.A.',
  'Mishimoto',
  'miss to mrs natural burlap banner',
  'misuse',
  'mitchell repair',
  'Mitchell Repair Information Company',
  'mkono',
  'mm-beachbody',
  'mobil car oil',
  'mobil thynthetic oil',
  'mobilefox',
  'mobilefox®',
  'MOCHOI',
  'Mocka Products Pty Ltd',
  'Moen',
  'moichef',
  'moko',
  'Monet Beauty Products LTD.',
  'moni originals',
  'monkey mountain',
  'monoprice',
  'monster cable',
  'monte',
  'Moolee',
  'moon boot',
  'mooneyes usa',
  'mooneyes usa inc.',
  'Mooneyes USA, Inc.',
  'moonrays',
  'moosaics',
  'Mophie',
  'mopnado',
  'mora',
  'mora companion',
  'morella',
  'moro led clip aquarium lights',
  'mors de bride',
  'Moshi',
  'mothercare',
  'motion picture associatio',
  'Motion Picture Association of America (MPAA)',
  'motion picture association of america mpaa',
  'motorola',
  'mounty',
  'move2play',
  'moviecraft',
  'Moviecraft Inc.',
  'movit',
  'mpaa',
  'mpow',
  'mpowerd',
  'mr blanc teeth',
  'mr clean',
  'mr coffee',
  'Mr. Clean',
  'mre',
  'Mroalk',
  'Mud Puppy Mold Company',
  'Multipure Int\'l',
  'muscle blast',
  'mustool®',
  'Mutbak',
  'mutbak durango',
  'My Pageant Kid',
  'My Pillow',
  'my poupette enterprises i',
  'My Poupette Enterprises Inc.',
  'mybeautycc',
  'MyGift Enterprise LLC',
  'MyPillow',
  'MySmile',
  'MyStudyGroup101',
  'Mywalit',
  'n.v.e.',
  'n.v.e. inc.',
  'N.V.E., Inc.',
  'nadinola',
  'NailRENEW Corp.',
  'nailstar',
  'Nandita Arts',
  'National Academy of Television Arts & Sciences',
  'national academy of television arts amp; sciences',
  'national board of medical',
  'National Board of Medical Examiners - NBME®',
  'National Board of Medical Examiners - NBMEÂ®',
  'national board of medical examiners nbme',
  'National Hardware',
  'national historic mining',
  'National Historic Mining Initiative LC3',
  'National Products Inc. DBA Ram Mounts',
  'national shooting sports',
  'National Shooting Sports Foundation',
  'nato',
  'Naturally Plus',
  'Nature’s Miracle',
  'natures greatest secret',
  'Nautilus',
  'nbme',
  'NCH Software',
  'NDS',
  'neal bearings',
  'neca',
  'Neewer',
  'neiko',
  'Nemoba',
  'Neocutis',
  'nescafe',
  'nespresso inissia espresso',
  'Nest',
  'netatmo',
  'netpicks',
  'netpicks llc',
  'NetPicks, LLC',
  'neue design',
  'neutrik ag',
  'new chapter',
  'New Era Cap Company',
  'new s\'well',
  'newbalans',
  'Nichols Photography',
  'nickolas muray photo archives llc',
  'Nickolas Muray Photo Archives, LLC',
  'nicorette',
  'nifty nozzles by sugar and crumbs',
  'nik',
  'Nike',
  'nike italy',
  'nikon',
  'ninepeak',
  'Ninja',
  'ninja 3in1 mc750',
  'Ninja Master',
  'ninja nutri',
  'nintendo',
  'Nintendo of America Inc.',
  'nissan',
  'Nissin Foods Holdings',
  'nite ize',
  'nitewatch',
  'Niwot Corporation dba Specialty Products Company',
  'nizamas gallery',
  'nizoral',
  'NOCO',
  'Noico',
  'nokia',
  'Nomex',
  'Nomination S.R.L.',
  'noodley\'s',
  'Nordic Naturals',
  'nordstrom',
  'nordstrom inc.',
  'Nordstrom, Inc.',
  'norton',
  'norwex',
  'NOW Foods',
  'nsk americas inc.',
  'NSK Americas, Inc.',
  'Nu Skin International Inc.',
  'Nucific',
  'NUTRAFOL - Nutraceutical Wellness, Inc.',
  'Nutramax Laboratories, Inc.',
  'nutrex',
  'nutri bullet',
  'nutri ninja',
  'NutriBullet',
  'nuzamas',
  'oakley',
  'oakley inc.',
  'Oakley, Inc.',
  'oaklyn',
  'oase',
  'oase (uk) ltd',
  'oase ltd',
  'obagi medical',
  'objet voyageur nocturne indispensable',
  'Oki Data Corporation',
  'oko-tex',
  'Öko-Tex',
  'olaplex',
  'Olay',
  'Old & Urban',
  'old amp; urban',
  'Old Spice',
  'omegaxl',
  'omiera',
  'omiera labs',
  'omyfilm',
  'one tigris',
  'One Two Cosmetics, LLC',
  'One Wise Mac Limited',
  'one1x',
  'onekubeddesigns',
  'onix',
  'OnlineFabricStore',
  'Ontel Products Corporation',
  'oojami',
  'oopsix',
  'opalescence',
  'Open University',
  'opi',
  'opi products',
  'opi products inc',
  'OPI Products, Inc',
  'opticron',
  'optimised energetics',
  'oral b',
  'Oral-B',
  'orange',
  'Orange USA',
  'orb life sciences',
  'orb life sciences llc',
  'Organo Gold',
  'oribe',
  'Orielle, LLC',
  'origami owl llc',
  'Origami Owl, LLC',
  'orlando digital telephone',
  'orobay',
  'orthotebb health shoes',
  'orthotebb health shoes llc',
  'Orthotebb Health Shoes, LLC',
  'Osmosis Skincare',
  'Osnat',
  'oster',
  'otc',
  'otron',
  'Otter Box',
  'Otterbox',
  'outlogiq',
  'Overstock.com Inc.',
  'ovni',
  'owl wonderland',
  'oxa 10 cups pitcher water filter',
  'oxgord',
  'OXO',
  'p rogers inc.',
  'P Rogers, Inc.',
  'pacific market internatio',
  'pacific market international llc',
  'Pacific Market International, LLC',
  'pacifica technologies inc',
  'Packard Club',
  'paddington',
  'Paddington and Company Limited',
  'pagedown technology',
  'pagedown technology llc',
  'Pagedown Technology, LLC',
  'Palksky',
  'Pamp SA',
  'pampered chef',
  'Pampered Chef, The',
  'Pampers',
  'panasonic',
  'panasonic corporation of',
  'Panasonic Corporation of North America',
  'Pantene',
  'pantheon',
  'paolo soleri',
  'paradise film institute',
  'Paradise Film Institute/Big Pictures',
  'Paradise Galleries',
  'paradise toys',
  'parblo pearl',
  'paris presents',
  'paris presents incorporated',
  'parker eight',
  'Pasoday Products Ltd',
  'Patch Collection, LLC',
  'Patch Me Thru',
  'Patchexpertsus',
  'patmont motor werks',
  'patmont motor werks/go ped',
  'Patmont Motor Werks/Go-Ped®',
  'Patmont Motor Werks/Go-PedÂ®',
  'paula deen',
  'paw patrol',
  'Pawsitively Perfect Bows',
  'pbpk',
  'PeachpopsClipArtâ„¢',
  'peachpopscliparttm',
  'PeachpopsClipArt™',
  'Peak Coffee Ltd',
  'pedalpro',
  'pen press',
  'Pen Press Publishing',
  'peng',
  'penrazor',
  'peppa pig',
  'Peppadew International',
  'pepper spray',
  'Pepto-Bismol',
  'performix',
  'peri k',
  'Peri K Designs',
  'peroom',
  'pestbye',
  'pestbye cat repellent',
  'pet eden',
  'pet ninja',
  'peter william ham',
  'petit h',
  'petninja',
  'petsafe',
  'pevonia international',
  'pevonia international llc',
  'Pevonia International, LLC',
  'Pfister',
  'phallosan',
  'phantom',
  'pharmatoka',
  'pharmedoc',
  'phatmojo',
  'philips electronics',
  'Philips Norelco',
  'philosophy',
  'philosophy inc.',
  'Philosophy, Inc.',
  'phiten',
  'Phiten GmbH',
  'Photomedex',
  'Piggy Pop',
  'pilestone',
  'Pillow Pad',
  'Pink Armor',
  'pinty',
  'piperwai llc',
  'PiperWai, LLC',
  'pipetto',
  'pivkey',
  'pk green',
  'Plans Designs',
  'Plarium Global LTD',
  'Platinum Place',
  'platypus wear',
  'platypus wear inc. dba bad boy brands',
  'Platypus Wear, Inc. dba Bad Boy Brands',
  'play platoon',
  'playboy',
  'Playboy Enterprises',
  'playstation',
  'playtex',
  'playtex products llc',
  'Playtex Products, LLC',
  'Plexaderm',
  'plexus',
  'plexus worldwide',
  'Plexus Worldwide, Inc',
  'Ploom - Pax Labs',
  'ploom pax labs',
  'plumeria',
  'plumeria bay inc.',
  'Plumeria Bay, Inc.',
  'pmd',
  'Pneumatic Components Ltd',
  'pneumaticcomponents',
  'Pocket Radar, Inc.',
  'pokemon',
  'pokonobe associates',
  'polished gentleman',
  'poly and bark',
  'polycom',
  'polymorphe',
  'polymorphe inc',
  'Polymorphe, Inc',
  'Pool Cover Corp. dba Loop Loc',
  'poppy',
  'Poppy Company',
  'popsockets',
  'PopSockets LLC',
  'porcelana',
  'Portage Word-Wide, Inc. - Manhattan Portage',
  'poshland',
  'Posture Doctor',
  'power art',
  'Power Art Design Airbrushs Pty Ltd',
  'Power Straight',
  'PowerPortLA, LLC',
  'powerstep',
  'practically darling',
  'Practically Darling Designs',
  'practico outdoors',
  'Prada S.A.',
  'pratico goods',
  'pratico goods llc',
  'Pratico Goods, LLC',
  'pratico kitchen',
  'pratipad',
  'pray and slay',
  'Premier League',
  'premium gallery',
  'premium led tactical flashlight kit',
  'premiumfishing auctions',
  'PremiumFishing Auctions Store',
  'Prescott Plastics, LLC',
  'presidio',
  'pretex',
  'primrose',
  'Princeton Nutrients',
  'pro tech',
  'proactiv',
  'Proactiv Company SÃ¡rl',
  'Proactiv Company Sárl',
  'Probiotic America',
  'procave',
  'procella',
  'Procter & Gamble',
  'Procter & Gamble Company',
  'prodiana',
  'product design patent',
  'professorprofits',
  'ProfessorProfits.com',
  'ProFroster',
  'prolux',
  'promescent',
  'prompter',
  'pronto moda global limite',
  'Pronto Moda Global Limited',
  'protool',
  'provo craft & novelty',
  'Provo Craft & Novelty, Inc.',
  'provo craft amp; novelty inc.',
  'ps3',
  'pu leather',
  'puffs',
  'puma',
  'pur',
  'pur rf',
  'puracy',
  'puracy natural',
  'Purdey',
  'pure-wave',
  'puregrace',
  'purest naturals',
  'pursonic',
  'PYLE',
  'qifit',
  'Quane Cosmetics',
  'Quanovate Tech, Inc. - Mira',
  'quantum networks',
  'quickcinch',
  'quickmount',
  'quiksilver',
  'quiksilver inc',
  'Quiksilver, Inc',
  'rachael ray',
  'Rachel Caine',
  'radiancy',
  'radiancy inc.',
  'Radiancy, Inc.',
  'Radio Flyer, Inc.',
  'Rainbow Sandals, Inc.',
  'Ram Cleaner',
  'randomwalk',
  'randomwalk llc',
  'Randomwalk, LLC',
  'ranger doug',
  'ranger doug #039;s enterprises',
  'Ranger Doug\'s Enterprises',
  'rapid.lash',
  'rare sportsfilms',
  'Rare Sportsfilms Inc.',
  'Rasasi Perfumes',
  'Ray Squad',
  'Ray-Ban',
  'Rayverstar LLC',
  'RAZER',
  'razormaid',
  'Razormaid! Productions',
  'RC Williams Company',
  'rdx',
  'rdx amara',
  'rdx inc',
  'rdx inc ltd',
  'rdz',
  're/max international',
  're/max international inc.',
  'RE/MAX International, Inc.',
  'Rea.Deeming Beauty, Inc. dba Beautyblender',
  'Real Flame',
  'real techniques',
  'reanice',
  'red bull',
  'Red Bull GmbH',
  'Red Camel Racing Ltd.',
  'red copper',
  'red digital cinema',
  'Red Digital Cinema Camera Company',
  'red hat',
  'red hat society inc',
  'Red Hat Society, Inc.',
  'red monkey',
  'red monkey designs inc.',
  'Red Monkey Designs, Inc.',
  'red steagall',
  'red steagall #039;s cowboy corner',
  'Red Steagall\'s Cowboy Corner',
  'redict',
  'Reditainer',
  'refrigiwear',
  'refund',
  'Relief Wrap Ultra',
  'relix international',
  'relix international inc.',
  'Relix International, Inc.',
  'Relleciga Official',
  'Rembrandt Charms',
  'reminderband',
  'ReminderBand Inc.',
  'Remington',
  'Remote Pro Pty Ltd',
  'renapur',
  'renegade gk',
  'Reshoevn8r',
  'resmed',
  'resort sleep',
  'revelation',
  'Revelation Records',
  'revenge',
  'Revitalash Cosmetics',
  'revlon',
  'revo',
  'rfid',
  'rgis',
  'RGK Innovations LLC',
  'rhino',
  'Rhodes International',
  'richard avedon',
  'Richard Avedon Foundation',
  'rideworx pty .',
  'Rideworx Pty Ltd.',
  'ridgerock',
  'Ridgerock Tools',
  'Right Deals UK Limited',
  'Rigid',
  'rinhoo',
  'RioRand',
  'rivers of health',
  'Rivington Designs Ltd',
  'rn study',
  'RN Study Spot',
  'roadpal',
  'rob dyrdek',
  'robert bosch llc',
  'robinson',
  'robotlife',
  'rocket science institute',
  'rocket science institute inc.',
  'Rocket Science Institute, Inc.',
  'rocky mountain vacuum',
  'Rodan',
  'rodan + fields',
  'Rohde Fine Art',
  'Roku',
  'rolf c. hagen, inc',
  'rolllra',
  'Rolls-Royce',
  'rolson',
  'ronaqua',
  'Rondofile',
  'rosetta stone',
  'Rosetta Stone (UK) Ltd',
  'rosotena',
  'Roth Company',
  'Rothstein Guitars',
  'roulis',
  'round_2brass',
  'Rowena Cherry',
  'Royal British Legion, The',
  'Royal Silk LTD',
  'RRO Entertainment',
  'rubbermaid',
  'rubiks cube',
  'rude awakening coffee hou',
  'Rude Awakening Coffee House',
  'Russell Hobbs',
  'rust-oleum',
  'rustler',
  'ruth louise dunn',
  'Ryohin Keikaku Co.,Ltd. - Muji',
  's\'well',
  's’well',
  'sac a dépêches',
  'Sacem',
  'Sado Nation',
  'sadowsky guitars',
  'Sadowsky Guitars Ltd.',
  'safeguard',
  'safiveih',
  'Sakura Color Products of America, Inc.',
  'Saleen',
  'Salt Gems LLC',
  'salt life holdings',
  'salt life holdings llc',
  'Salt Life Holdings, LLC',
  'SaltWorks, Inc.',
  'samsung',
  'sanddisk',
  'sandisk',
  'sanggol',
  'sani stick',
  'Santas Christmas Town',
  'sanyo electric',
  'sanyo electric co. ltd.',
  'Sanyo Electric Co., Ltd.',
  'SAP',
  'Sara Moon',
  'sara noon',
  'sarah lough',
  'savanna group',
  'Savanna Group LTD - Savanna Samson',
  'savanna group ltd savanna samson',
  'savanna samson',
  'save n save',
  'Savvy Turtle Inc',
  'sbg revo',
  'sbg revo holdings llc',
  'ScanTool.net, LLC',
  'scaredy cut',
  'schlyer',
  'Schlyer Designs',
  'schulter kerdi-band',
  'Schwabel',
  'Scope',
  'scotabc',
  'scotch',
  'Scottcrew Enterprises',
  'scrolling license plate p',
  'scrolling license plate patent infringement',
  'scs',
  'SD Biotechnologies',
  'sea to summit',
  'sealed air',
  'sealed air corporation',
  'sealey',
  'Searching for Louis Media',
  'Seat Belt Extender',
  'seatosummit',
  'Secret',
  'secret of art',
  'Secret-of-Art',
  'seeing with sound - the v',
  'Seeing with Sound - The vOICe',
  'seeing with soundvoice',
  'segmart',
  'SEISCO International Limited',
  'self defense',
  'Sennheiser',
  'senrob',
  'Sensation Press',
  'Sensual Candle',
  'Sephra',
  'serrated',
  'Seven Towns',
  'sevenhills wholefoods',
  'seventh generation baby diaper',
  'sevicat',
  'sew terific',
  'Sew Terific Designs',
  'Sewing Bee Crinoline Ladies Embroidery Patterns',
  'Shabby Chic',
  'shadow river sales',
  'Shark',
  'sharkninja',
  'sharkninja operating llc',
  'shavette',
  'sheetworld',
  'shells',
  'sheridan douglas',
  'Sheridan Douglas Press',
  'Shewee Ltd',
  'shimano inc',
  'Shimano, Inc',
  'Shiseido Company Limited',
  'shop vac',
  'Shop Vac Corporation',
  'shunzaor',
  'Shure',
  'sientra, inc',
  'sierra madre supplies',
  'siesco',
  'siesco international limited',
  'sight',
  'Sigma',
  'Sigma Beauty',
  'sigma enterprises llc',
  'sigmacumlaude',
  'Sigmacumlaude.com',
  'siia',
  'silicon beauty blen',
  'silkycity',
  'similac',
  'Simon Carey',
  'simpeak',
  'simple fit',
  'Simple human',
  'Simplehuman',
  'Simpler Trading, LLC',
  'simplicam',
  'simply fit board',
  'Simply Straight',
  'singer',
  'Sinister Mfg. Co., Inc. (Sinister Diesel)',
  'sinland',
  'sinopuren',
  'sir perky',
  'Siser',
  'Skechers',
  'sketchers',
  'skiboards superstore',
  'skiboards superstore inc.',
  'Skiboards Superstore, Inc.',
  'skinscience',
  'skip hop',
  'skip-hop',
  'Sky Deutschland Fernsehen GmbH & Co. KG',
  'sky viper',
  'skyroof',
  'slendertone',
  'slidebelts',
  'slim xtreme',
  'slimbelly',
  'smarterfresh',
  'smarterfresh llc',
  'SmarterFresh, LLC',
  'smartsound',
  'smartsound software inc.',
  'SmartSound Software, Inc.',
  'smellfree cat',
  'smoke blaster',
  'sms audio',
  'sms audio llc',
  'SMS Audio, LLC',
  'snakeemporium',
  'SnakeEmporium.com',
  'snap on incorporated',
  'Snap-On',
  'Snap-on Incorporated',
  'SnapOn',
  'snb react ne rlands',
  'snb-react',
  'sneaker balls',
  'snowera',
  'SnugglyCat Inc - The Ripple Rug',
  'snugglycat incripple rug',
  'society for human resourc',
  'Society for Human Resource Management',
  'SockDock, LLC',
  'soclean',
  'SoClean, Inc.',
  'sof comfort',
  'sof sole',
  'Software & Information Industry Association (SIIA)',
  'software amp; information industry association siia',
  'solascape',
  'sole technology',
  'sole technology inc.',
  'Sole Technology, Inc.',
  'solemates',
  'soles2dance',
  'solid ventures',
  'solid ventures,',
  'solmate socks',
  'SoloWork Studio',
  'solwise',
  'songmics',
  'Sony',
  'sony ericsson mobile comm',
  'Sony Ericsson Mobile Communications AB',
  'sonyplastation',
  'Sorona',
  'soundasleep',
  'sout',
  'southwest entertainment g',
  'southwest pictures',
  'southwest pictures / southwest entertainment group llc',
  'Southwest Pictures / Southwest Entertainment Group, LLC',
  'soyoko',
  'sparkles make it special',
  'spatula',
  'Speck',
  'speck products',
  'Speed Out',
  'spenco',
  'SpiceFit',
  'spicer pro',
  'spicer pro llc',
  'Spicer Pro, LLC',
  'spigen',
  'Spin Master',
  'spiralife',
  'spirid creation',
  'Sprint Corporation',
  'spy crushers',
  'spyder active sports',
  'spyder active sports inc.',
  'Spyder Active Sports, Inc.',
  'Square',
  'squatty potty, llc',
  'srixon',
  'stanaley',
  'Standard Innovation Corporation',
  'stanley',
  'Star Alliance Services GmbH',
  'Star Kids',
  'star shower as seen on tv motion laser lights star projector',
  'star trek next gen mugs - sciences',
  'star wars',
  'star wars hoth dinner set',
  'starrich',
  'station 22',
  'stealth',
  'steeple',
  'stephen shore',
  'Stephen Shore, photographs',
  'sterilite',
  'stokke',
  'store your board',
  'strenco',
  'stromberg carburetor',
  'Stromberg Carburetor Ltd.',
  'Strutz',
  'STS Industries Inc. - NageBee',
  'studiojenkins works',
  'stussy inc',
  'Stussy Inc.',
  'STV Motorsports LLC',
  'STX INTERNATIONAL',
  'stylebreaker',
  'Styrofoam',
  'suddora llc',
  'Sue Coffee',
  'sugru',
  'Sugru (FormFormForm Ltd)',
  'sukoa',
  'summer infant',
  'SummitFashions',
  'Suncast Corporation',
  'sunnors',
  'Sunrider International',
  'suntana',
  'suntana spray tan',
  'Supacaz',
  'super power supply',
  'super sunnies',
  'Superchips',
  'superior abohone',
  'superior glutes',
  'Superior Products USA LLC',
  'sure plug',
  'Surgi Corp',
  'Surgical Appliance Industries, Inc.',
  'surplus deal usa',
  'Susan Lough',
  'sushi bazooka',
  'SuZhou Aobani Trading Company Ltd.',
  'Swanson Health Products',
  'swarovski',
  'swarovski ag',
  'Swarovski North America Limited',
  'swell',
  'Swiffer',
  'Swift Response, LLC',
  'swimbest',
  'Swing Set Stuff',
  'swiss army brands',
  'swiss army brands inc.',
  'Swiss Army Brands, Inc.',
  'swisselite',
  'Swivel Sweeper',
  'sy xiongdi',
  'Sylver Designs',
  'Symantec',
  'Synergetics',
  'synergy computing busines',
  't-fal',
  't?',
  't3 micro inc',
  'TÃ¼v SÃ¼d',
  'taclight',
  'Tactical Beard Owners Club (TBOC)',
  'tactical rescue pocket knife',
  'tacvasen',
  'tad bits baby items and more llc',
  'tad-bits baby items',
  'Tad-Bits Baby Items and More LLC',
  'Takata Corporation',
  'talavera hair products',
  'talinu',
  'talon',
  'tamiya america',
  'tamiya america inc.',
  'Tamiya America, Inc.',
  'Tampax',
  'Tangle Teezer',
  'Tania R. Chase',
  'tanita',
  'tanner',
  'TÃœV Markenverbund e.V',
  'taotronics',
  'tasco sales',
  'taser international',
  'taser international inc',
  'TASER International Inc.',
  'taya',
  'teak shower',
  'team mysterio',
  'team mysterio inc.',
  'Team Mysterio, Inc.',
  'Teami Blends',
  'tecaroo',
  'tech traders',
  'techcomm',
  'technica usa',
  'Technica USA (Moon Boot)',
  'technica usa moon boot',
  'technical video',
  'technical video llc',
  'Technical Video, LLC',
  'Technopack Corporation (Jorestech)',
  'techsmith',
  'TechSmith Corporation',
  'Tecscan of North Florida, Inc.',
  'teebereiter',
  'teeter',
  'teeter better back vibration cushion',
  'tekay designs',
  'Tekay Designs Inc.',
  'tekcoo',
  'telebrands',
  'telebrands corporation',
  'test - dont delete me',
  'Tetra',
  'That\'s Greenius, LLC',
  'the bradvica company',
  'the cellulite myth',
  'the collectors addition',
  'the estate',
  'the ferret company',
  'the glowhouse ltd',
  'the gretsch company',
  'the gro company',
  'the heirs and estate',
  'The Himalaya Drug Company',
  'The Jewelry Channel Inc. dba Shop LC',
  'The Juice Plus, Company',
  'The Juice Plus+ Company',
  'The LifeVantage Corporation',
  'the national academy of t',
  'The Neck Hammock',
  'the noodley',
  'the open university',
  'the perfect cosmetics company',
  'the premier league',
  'the product hatchery,',
  'The Richemont Group',
  'the sensual candle',
  'the sewing bee crinoline',
  'the software & informatio',
  'Thea Gouverneur BV',
  'Thermacell',
  'thermapen',
  'These Please Ltd',
  'thin blue',
  'thin optics stick',
  'Things 4 Strings LLC',
  'thinoptics',
  'third man',
  'Third Man Records',
  'Thomas Losh',
  'thread a bead',
  'thread-a-bead',
  'ThreadABead',
  'three dogs and a cat',
  'Three Dogs and a Cat Inc.',
  'Thule',
  'Tide',
  'TidyEmu',
  'Tiffany & Company',
  'tiffany amp; company',
  'tiger tom pistone race ca',
  'Tiger Tom Pistone Race Cars & Parts',
  'tiger tom pistone race cars amp; parts',
  'Tiger Wrench',
  'TigerDirect',
  'timbuk2',
  'time tracker',
  'Time Tracker Technology',
  'timex',
  'titleist',
  'tmh technology',
  'tmh technology co. ltd.',
  'TMH Technology Co., Ltd.',
  'To Your Home Ltd',
  'tokentools',
  'Tokentools Pty Ltd',
  'tokyoflash',
  'TokyoFlash Japan',
  'tom kelley studios',
  'tom kelley studios inc.',
  'Tom Kelley Studios, Inc.',
  'tomei powered usa',
  'Tomei Powered USA Inc.',
  'Tommie Copper',
  'Tommy Hilfiger',
  'Tommy Hilfiger Licensing BV',
  'toorun',
  'top dog chews',
  'top greener',
  'Top Secret Recipes',
  'topgreener',
  'topmax',
  'topnotch designs us',
  'tori richard',
  'tori richard ltd.',
  'Tori Richard, Ltd.',
  'torro cases',
  'Total Family Ministries',
  'Total Gym',
  'total tea',
  'totalpack',
  'totaltea',
  'totaltea_us',
  'Tottenham Hotspur Ltd',
  'ToughCOINS LLC',
  'tpc',
  'traeger',
  'trafellows',
  'TrailerSauce',
  'trainingmask',
  'trainingmask llc',
  'Trainingmask, LLC',
  'transcender',
  'travel rest',
  'travelrest',
  'tre milano, llc',
  'treasured hungarian famil',
  'Treasured Hungarian Family Recipes TM',
  'treasured hungarian family recipestm',
  'treat my feet',
  'Trebco',
  'treefrog',
  'trendy fleece tots',
  'tribord',
  'trident',
  'triggerpoint',
  'trillium',
  'trinity',
  'triple cs supplements',
  'tristar products',
  'trolley bags uk',
  'trolley bags uk ltd',
  'troy',
  'troy indrustries',
  'true',
  'True Religion',
  'Trunki',
  'TRX',
  'trx go',
  'Tshirt Bordello',
  'tuffy',
  'Tuft & Needle',
  'turban plus',
  'Turbo Jet',
  'Turbo Pump',
  'Turbo Scrub',
  'Turbo Snake',
  'Turbosmart',
  'turbotax',
  'TÜV Markenverbund e.V',
  'Tüv Süd',
  'tw steel',
  'tweexy',
  'twilly d\'hermes',
  'Twinkl Ltd',
  'tyger',
  'tylt',
  'tyme llc',
  'Tyvek',
  'uboxes',
  'UBOXES, LLC',
  'ugears',
  'ugg holding',
  'ugg holdings inc.',
  'UGG Holdings, Inc.',
  'uggs',
  'ugs corp',
  'UGS Corp.',
  'ulead systems',
  'ultimate creations',
  'ultimate creations inc./ ultimate warrior/warrior',
  'Ultimate Creations, Inc. / Ultimate Warrior / Warrior',
  'Ultimate Pet Nutrition, LLC',
  'ultimate sports franchise',
  'Ultimate Sports Franchise Agents',
  'ultimate warrior',
  'Ultra Glow Cosmetics LTD',
  'Ultra Herbal',
  'ultradent',
  'ultramax products',
  'Ultramax Products Limited',
  'ultranatura',
  'ultrasport',
  'ultratec',
  'umbro international limit',
  'Umbro International Limited',
  'umtele',
  'Underwriters Laboratories, Inc.',
  'uni',
  'Uni-Trend Technology Co., Ltd',
  'unicorn cosmetics',
  'United Pet',
  'United States Forest Service - USDA',
  'united states forest service usda',
  'University of Iowa',
  'unker\'s',
  'upanaway',
  'urban fusion',
  'urbane men',
  'urcover',
  'urcover®',
  'ursula hock henschke',
  'Ursula Hock-Henschke',
  'usa toyz',
  'uspackshop',
  'utg',
  'utopia',
  'utopia kitchen',
  'uzitec',
  'v-cen',
  'Vacheron Constantin',
  'vacnite',
  'Vale Science Technology Co. Ltd',
  'valneo',
  'Vampire Squid Cards',
  'Van Cleef & Arpels',
  'vanage',
  'vanguard industries',
  'vanguard industries inc.',
  'Vanguard Industries, Inc.',
  'vaunn',
  'vega 911',
  'Veggetti',
  'Veggetti Power',
  'Veggetti Pro',
  'velcro',
  'velcro brand',
  'velcro closure',
  'Velcro Companies',
  'velcro industries',
  'velcro industries b.',
  'velcro industries b. v',
  'velcro industries b. v.',
  'velux',
  'ven-ex snake bite kit, bee sting kit, emergency first aid supplies, venom extrac',
  'vena',
  'venalisa',
  'venjoin.com',
  'venjoin.com llc',
  'Vera Bradley',
  'Versace',
  'VersaLiving',
  'viahart',
  'vickie milazzo',
  'Vickie Milazzo Institute',
  'Vicks',
  'victorinox',
  'victory seed',
  'Victory Seed Co.',
  'vidal sassoon',
  'vidbidness',
  'Vietnam International Video',
  'vikingstrength',
  'vinani',
  'vintage cigarette',
  'Vintage Cigarette Lighters',
  'vintage fans',
  'vintage fans l.l.c.',
  'Vintage Fans, L.L.C.',
  'vinyl',
  'vinyl ease',
  'vinyl ease llc',
  'vip products',
  'Viper Interactive',
  'Virgil C. Stephens',
  'Vitagene, Inc',
  'vitamix',
  'vitazoo',
  'vivint inc.',
  'Vivint, Inc.',
  'vivosun',
  'vkr holding',
  'VKR Holding A/S (VELUX)',
  'Volkswagen Corporation',
  'vonhaus',
  'voron',
  'Vortex Optics',
  'voyage d\'hermes',
  'Vtooland',
  'VWAQ',
  'vxi',
  'vxi blueparrott',
  'vyncs',
  'WÃ¼rth Srl',
  'wacom',
  'wacom intuos',
  'wagberry',
  'wahl',
  'walcase',
  'walgroup llc',
  'walker metalsmiths c',
  'Walker Metalsmiths Celtic Jewelry',
  'Walnut Studiolo LLC',
  'wandeneng',
  'Ware Family Genealogy',
  'warmawear',
  'warne',
  'Warner Music Group',
  'Warner\'s Blue Ribbon Books on Swarovski',
  'watch tower bible and tract society of pennsylvania',
  'watch ya mouth',
  'water pik',
  'water pik inc',
  'Water Pik, Inc',
  'waterpik',
  'Wax Liquidizer Ltd.',
  'wd music products',
  'wd music products inc.',
  'WD Music Products, Inc.',
  'wearme pro',
  'WeatherTech',
  'Weber',
  'weinstein company',
  'Weinstein Company, The',
  'Weiser',
  'wellb4',
  'wenfeng',
  'West American Corporation d/b/a RBH Sound',
  'West Frames, Inc.',
  'Westin',
  'westpack shop 3/16" 175 ft x 12" small bubble cushioning wrap, perforated every 12"',
  'WH Software Limited',
  'What Do You Meme',
  'what do you meme, llc',
  'whelen engineering compan',
  'whelen engineering company inc.',
  'Whelen Engineering Company, Inc.',
  'whink',
  'whirlpool',
  'whirlpool properties, inc.',
  'white collar',
  'whizardries',
  'whizardries inc.',
  'Whizardries, Inc.',
  'Whole Body Research, LLC',
  'wicked chili',
  'wiggles touring',
  'wiggles touring pty limited',
  'Wiggles Touring Pty Limited, The',
  'wild thera',
  'William Mark',
  'windmill parts.com',
  'windmill-parts',
  'Windmill-Parts.com',
  'wintex',
  'Wisdom of the Ages',
  'With You Designs, LLC and With You Lockets',
  'wix',
  'wod',
  'wod toys',
  'wodtoys',
  'woldoclean',
  'wonder home gardens - whg',
  'Wonder Wizards',
  'woombie',
  'world hockey association',
  'world hockey association llc',
  'World Hockey Association, LLC',
  'world wrestling entertain',
  'world wrestling entertainment inc. wwe',
  'World Wrestling Entertainment, Inc. (WWE)',
  'Worldwide Women Artists (WWAO)',
  'worx',
  'wow apple cider',
  'Wow Cup',
  'Wow Gear',
  'WowWee',
  'WowWee Group Ltd',
  'WRIST-ROCKET',
  'WristWidget',
  'wstechco',
  'WubbaNub',
  'wuppertal-solingen remsch',
  'Würth Srl',
  'wwe',
  'wwe raw main event ring',
  'www.cutecolors.com',
  'www.danworkshop.com',
  'www.snakeemporium.com',
  'Wyndmere',
  'X Bats',
  'x mini capsule speakers',
  'X-mini Capsule Speakers',
  'x-senkry',
  'xbmc',
  'XBMC Solutions Ltd - Droidbox',
  'xelotech',
  'xiangzhiheng electronics',
  'Xiangzhiheng Electronics Inc.',
  'xpose safety',
  'xpressmart',
  'XPressMart.com',
  'xujinhao',
  'y amp;t meniketti',
  'Y&T - Meniketti',
  'yaktrax',
  'Yamaha Corporation of America',
  'Yankee Candle',
  'yens elite',
  'YODE',
  'yoga toes',
  'yogabody',
  'Yogitoes',
  'Younghair AB LTD',
  'younique llc',
  'Younique, LLC',
  'your baby can',
  'your baby can llc.',
  'Your Baby Can, LLC.',
  'youshiko',
  'yowei',
  'yubo technology',
  'Yubo Technology Co.Ltd.',
  'yum! brands inc.',
  'Yum! Brands, Inc.',
  'Yvonne Hedley',
  'Z Produx Inc.',
  'Z-Man Fishing Products, Inc.',
  'zacurate',
  'zadro product inc',
  'ZAGG',
  'Zamboni',
  'zantech',
  'zappos',
  'Zappos.com',
  'Zen Design Group Ltd',
  'zen water filter',
  'zento',
  'zenzoi',
  'Zephyr Vaporizers',
  'zepp',
  'zepp labs',
  'zero grid',
  'zesproka',
  'Zhao Xiang',
  'Zip gun',
  'Zip Top',
  'zodiac watches',
  'zookie',
  'zosi',
  'zulu bunch of baloons',
  'Zumba',
  'zumba fitness',
  'zuru ltd',
  'zxz',
  'zyliss',
  'Zzzquil'
];

// Restricted words from eBay policy
const RESTRICTED_WORDS = [
  'trousers',
  'blouse',
  't-shirt',
  'sweater',
  'jacket',
  'coat',
  'shorts',
  'sweatpants',
  'skirt',
  'dress',
  'hoodie',
  'underwear',
  'socks',
  'tights',
  'swimwear',
  'leggings',
  'cardigan',
  'tank top',
  'blazer',
  'polo',
  'jumper',
  'leotards',
  'robe',
  'tunic',
  'bodysuit',
  'vest',
  'windbreaker',
  'culottes',
  'pajamas',
  'gloves',
  'hat',
  'beanie',
  'scarf',
  'tie',
  'belts',
  'capris',
  'kimonos',
  'overalls',
  'slacks',
  'stockings',
  'peacoat',
  'bra',
  'briefs',
  'boxers',
  'shawl',
  'knee highs',
  'thong',
  'turtleneck',
  'bandana',
  'balaclava',
  'beret',
  'bomber jacket',
  'bustier',
  'caftan',
  'cape',
  'cashmere sweater',
  'corduroy pants',
  'cowl neck sweater',
  'denim jacket',
  'dungarees',
  'flannel shirt',
  'fleece jacket',
  'gilet',
  'henley shirt',
  'high waisted jeans',
  'jumpsuit',
  'kaftan',
  'knit cap',
  'leather jacket',
  'lingerie',
  'mittens',
  'necktie',
  'parka',
  'poncho',
  'puffer jacket',
  'raincoat',
  'rash guard',
  'rompers',
  'sarong',
  'shapewear',
  'sheath dress',
  'sherpa jacket',
  'silk scarf',
  'snowsuit',
  'sports bra',
  'stetson hat',
  'straw hat',
  'suede jacket',
  'sun hat',
  'suspenders',
  'tweed jacket',
  'umbrella',
  'velvet dress',
  'waistcoat',
  'windbreaker jacket',
  'wool coat',
  'wool hat',
  'yoga pants',
  'zentai',
  'pants',
  'shirt',
  'pant',
  'jean',
  'joggers',
  'tracksuit bottoms',
  'waist',
  'tee',
  'flip-flop',
  'flipflop',
  'shoe',
  'shoes',
  'sneakers',
  'boots',
  'sandals',
  'slippers',
  'heels',
  'pumps',
  'stilettos',
  'loafers',
  'moccasins',
  'oxfords',
  'brogues',
  'clogs',
  'espadrilles',
  'mules',
  'ankle boots',
  'knee high boots',
  'thigh high boots',
  'ballet flats',
  'gladiators',
  'platform shoes',
  'running shoes',
  'trainers',
  'gym shoes',
  'hiking boots',
  'snow boots',
  'flip flops',
  'slides',
  'crocs',
  'deck shoes',
  'boat shoes',
  'derby shoes',
  'monk shoes',
  'wellington boots',
  'combat boots',
  'chelsea boots',
  'chukka boots',
  'cowboy boots',
  'dress shoes',
  'wedge sandals',
  'birkenstocks',
  'slingbacks',
  'mary janes',
  'jellies',
  'steel toe boots',
  'wingtips',
  'work boots',
  'duck boots',
  'riding boots',
  'high top sneakers',
  'low top sneakers',
  'basketball shoes',
  'football cleats',
  'golf shoes',
  'tennis shoes',
  'cycling shoes',
  'dance shoes',
  'pointe shoes',
  'tap shoes',
  'roller skates',
  'ice skates',
  'water shoes',
  'wrestling shoes',
  'climbing shoes',
  'trainer',
  'loafer',
  'oxford',
  'short',
  'womens straight',
  'brief',
  'hood',
  'womens a-line',
  'classic-fit',
  'tight',
  'sock',
  'suit',
  'bikini',
  'swimsuit',
  'outfit',
  'camisole',
  'slim-fit',
  'v-neck',
  'long sleeve',
  'legging',
  'pajama',
  'sleepwear',
  'leotard',
  'nejor',
  'cap',
  'pyjamas',
  'fleece',
  'jersey',
  'capri',
  'kimono',
  'sleeve',
  'mens classic',
  'womens modern',
  'hosiery',
  'fishnet',
  'thigh highs',
  'womens casual',
  'cotton stretch',
  'boxer',
  'pullover',
  'bomber',
  'gaiter',
  'rashguard',
  'dungaree',
  'gambler',
  'cocktail',
  'womens wrap',
  'jogger',
  'straight fit',
  'sandal',
  'slide',
  'flip flop',
  'chemise',
  'slim fit',
  'mens core',
  'men\'s classic',
  'backseam',
  'boot',
  'playstation'
];

// Compatibility Keywords (allow these even for VERO brands)
const COMPATIBILITY_KEYWORDS = [
  'for', 'compatible with', 'fits', 'replacement for', 'works with', 'designed for',
  'case for', 'cover for', 'charger for', 'cable for', 'accessory for', 'screen protector for',
  'stand for', 'mount for', 'holder for', 'adapter for', 'sleeve for', 'bag for', 'strap for', 'band for',
  'replacement', 'generic', 'aftermarket', 'third party', 'non-oem', 'compatible', 'alternative'
];

// Banned Items Keywords
const BANNED_KEYWORDS = [
  // Medical/Drug
  'syringes', 'needles', 'hypodermic', 'drug paraphernalia', 'bongs', 'pipes', 'rolling papers',
  'prescription medication', 'controlled substances', 'steroids', 'human growth hormone', 'HGH',
  // Weapons
  'firearms', 'guns', 'rifles', 'pistols', 'ammunition', 'ammo', 'bullets', 'explosives', 'grenades', 'bombs',
  'fireworks', 'stun guns', 'tasers', 'brass knuckles', 'switchblade', 'butterfly knife', 'balisong',
  'throwing stars', 'nunchucks', 'blackjack', 'slingshot', 'crossbow',
  // Dangerous
  'poison', 'toxic', 'hazardous materials', 'asbestos', 'radioactive', 'mercury', 'cyanide',
  // Fraud
  'counterfeit', 'fake', 'replica', 'knockoff', 'bootleg', 'pirated', 'stolen', 'clone',
  // Recalled
  'recalled', 'banned by FDA', 'banned by CPSC', 'safety recall',
  // Adult
  'adult content', 'pornography', 'explicit', 'xxx', 'sex toy', 'escort services',
  // Living
  'live animals', 'human remains', 'body parts', 'organs',
  // Services
  'gift cards', 'digital downloads', 'software keys', 'license codes',
  // Government
  'police badges', 'government ID', 'passport', 'driver license', 'social security', 'military insignia',
  // Tobacco/Alcohol
  'cigarettes', 'tobacco', 'vape', 'e-cigarette', 'alcohol', 'wine', 'beer', 'liquor'
];

// Fragile/Liquid Keywords
const FRAGILE_KEYWORDS = [
  'glass', 'ceramic', 'porcelain', 'crystal', 'mirror', 'china', 'delicate', 'breakable', 'fragile',
  'liquid', 'gel', 'oil', 'lotion', 'cream', 'spray', 'perfume', 'cologne', 'serum', 'toner', 'cleanser',
  'shampoo', 'conditioner', 'body wash', 'soap', 'nail polish', 'paint', 'ink', 'dye',
  'bottle', 'jar', 'candle', 'diffuser'
];

/**
 * Check if product passes all compliance filters
 * Returns detailed results with reasons for any failures
 */
export function checkCompliance(product: AmazonProduct): ComplianceResult {
  const reasons: string[] = [];
  const filtersFailed: string[] = [];
  let riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' = 'LOW';

  // FILTER 1: VERO Brands Check (CRITICAL - Cannot Disable)
  const veroResult = checkVERO(product);
  if (!veroResult.passed) {
    reasons.push(veroResult.reason);
    filtersFailed.push('vero_brands');
    riskLevel = 'CRITICAL';
  }

  // FILTER 2: Banned Items Check (CRITICAL - Cannot Disable)
  const bannedResult = checkBannedItems(product);
  if (!bannedResult.passed) {
    reasons.push(bannedResult.reason);
    filtersFailed.push('banned_items');
    riskLevel = 'CRITICAL';
  }

  // FILTER 3: Price Threshold Check
  if (product.price < 5 || product.price > 500) {
    reasons.push(`Price out of range: $${product.price} (acceptable: $5-$500)`);
    filtersFailed.push('price_threshold');
    riskLevel = 'HIGH';
  }

  // FILTER 4: Margin Check (minimum 15% net margin)
  // Assuming 2x markup: eBay price = Amazon price * 2
  // Net margin = (eBay price - Amazon price - fees) / eBay price
  // With 2x markup and ~12.9% eBay fees: margin ≈ 43%
  // But we need minimum 15% to be safe
  const ebayPrice = product.price * 2;
  const ebayFees = ebayPrice * 0.129; // ~12.9% eBay fees
  const netMargin = ((ebayPrice - product.price - ebayFees) / ebayPrice) * 100;
  if (netMargin < 15) {
    reasons.push(`Margin too low: ${netMargin.toFixed(1)}% (minimum: 15%)`);
    filtersFailed.push('margin_check');
    riskLevel = 'HIGH';
  }

  // FILTER 5: Review Count Minimum (10 reviews)
  if (product.reviewCount < 10) {
    reasons.push(`Insufficient reviews: ${product.reviewCount} (minimum: 10)`);
    filtersFailed.push('review_count');
    riskLevel = 'MEDIUM';
  }

  // FILTER 6: Rating Minimum (3.5 stars)
  if (product.rating < 3.5) {
    reasons.push(`Rating too low: ${product.rating} stars (minimum: 3.5)`);
    filtersFailed.push('rating_minimum');
    riskLevel = 'HIGH';
  }

  // FILTER 7: Title Keyword Blacklist
  const titleLower = product.title.toLowerCase();
  for (const keyword of FRAGILE_KEYWORDS) {
    if (titleLower.includes(keyword)) {
      reasons.push(`Fragile/liquid item detected: contains "${keyword}"`);
      filtersFailed.push('fragile_liquid');
      riskLevel = 'HIGH';
      break;
    }
  }

  const passed = filtersFailed.length === 0;

  return {
    passed,
    reasons,
    riskLevel,
    filtersFailed
  };
}

/**
 * Check if product is a VERO-protected brand
 */
function checkVERO(product: AmazonProduct): { passed: boolean; reason: string } {
  const titleLower = product.title.toLowerCase();
  const brandLower = (product.brand || '').toLowerCase();

  // Check if it's a compatible accessory (allowed even for VERO brands)
  if (isCompatibleAccessory(product.title)) {
    return {
      passed: true,
      reason: 'Compatible accessory - allowed'
    };
  }

  // Check against VERO brand list
  for (const brand of VERO_BRANDS) {
    const brandCheck = brand.toLowerCase();
    if (titleLower.includes(brandCheck) || brandLower === brandCheck) {
      return {
        passed: false,
        reason: `VERO protected brand detected: ${brand}`
      };
    }
  }

  return {
    passed: true,
    reason: 'No VERO brand detected'
  };
}

/**
 * Check if product is a compatible accessory
 */
function isCompatibleAccessory(title: string): boolean {
  const titleLower = title.toLowerCase();
  return COMPATIBILITY_KEYWORDS.some(keyword => titleLower.includes(keyword));
}

/**
 * Check if product contains banned items
 */
function checkBannedItems(product: AmazonProduct): { passed: boolean; reason: string } {
  const contentToCheck = `${product.title} ${product.description || ''}`.toLowerCase();

  // Check banned keywords
  for (const keyword of BANNED_KEYWORDS) {
    if (contentToCheck.includes(keyword.toLowerCase())) {
      return {
        passed: false,
        reason: `eBay banned item detected: contains "${keyword}"`
      };
    }
  }

  return {
    passed: true,
    reason: 'No banned items detected'
  };
}

/**
 * Get risk level color for Discord messages
 */
export function getRiskLevelColor(riskLevel: string): number {
  switch (riskLevel) {
    case 'LOW':
      return 0x00FF88; // Green
    case 'MEDIUM':
      return 0xFFD700; // Gold
    case 'HIGH':
      return 0xFF8C00; // Orange
    case 'CRITICAL':
      return 0xFF0000; // Red
    default:
      return 0x808080; // Gray
  }
}

/**
 * Get risk level emoji
 */
export function getRiskLevelEmoji(riskLevel: string): string {
  switch (riskLevel) {
    case 'LOW':
      return '✅';
    case 'MEDIUM':
      return '⚠️';
    case 'HIGH':
      return '🔴';
    case 'CRITICAL':
      return '🚨';
    default:
      return '❓';
  }
}
